### PR TITLE
Example of Abi with enums of Cairo v2.0

### PR DESCRIPTION
**Pull request by PhilippeR26**
## Motivation and Resolution
Cairo v2.0 is now implementing new types in the abi : 
Extract of cairo v2.0 code :
```rust
pub enum Item {
    #[serde(rename = "function")]
    Function(Function),
    #[serde(rename = "constructor")]
    Constructor(Constructor),
    #[serde(rename = "l1_handler")]
    L1Handler(L1Handler),
    #[serde(rename = "event")]
    Event(Event),
    #[serde(rename = "struct")]
    Struct(Struct),
    #[serde(rename = "enum")]
    Enum(Enum),
    #[serde(rename = "interface")]
    Interface(Interface),
    #[serde(rename = "impl")]
    Impl(Imp),
}
```
## Usage related changes

N/A

## Development related changes

This PR add a contract in __mocks__/cairo/enum.
This contract generates a sierra file, containing an abi that covers all the inputs seen above.
The abi contains : 
- a specific enum
- a core::Option enum
- a core::Result enum

the enums contains litterals and structs.

This abi can be used in the future for tests.

## Checklist:

- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Linked the issues which this PR resolves
- [x] Documented the changes in code (API docs will be generated automatically)
- [x] Updated the tests
- [x] All tests are passing

### CODE REVIEW

**Comment by tabaktoni** [comment]
We have basic enum for testing in /helloCairo2, can you add your cases to that contract?

**Comment by PhilippeR26** [comment]
Seems to be no enum in helloCairo2.
Anyway, I will merge all new things of my code in helloCairo2.

**Comment by PhilippeR26** [comment]
I added in the helloCairo2 :
- custom enum
- Option Enum
- constructor
- l1_handler

I didn't added Result, as it's not implemented in cairo v2.0.0 (will be implemented later)

**Comment by PhilippeR26** [comment]
As this contract has been added after my PR, I have difficulties with git.
I cancel this PR, and propose a new one, based on a config including helloCairo2.

**Pull request closed without merging**
