### PR TITLE
fix(provider): getBlock, replace blockId to blockHash

### LINKED ISSUE #120: getBlock with custom block id always return latest block
Using the function getBlock() with a custom block number it doesn't return the correct block example:
https://alpha-mainnet.starknet.io/feeder_gateway/get_block?blockId=123

### PR DESCRIPTION
**Pull request by bonustrack**
The param blockId doesn't seem to be working anymore on the getBlock function, this PR replace it to blockHash.

Fix #120

### CODE REVIEW

**Review by janek26 — APPROVED** [review]
thank you!

**Comment by janek26** [comment]
can you please start from `develop` or rebase?

**Review by janek26 — CHANGES_REQUESTED** [review]
can you please start from develop or rebase?

**Comment by bonustrack** [comment]
Thanks, closing this PR it seem that it's already handled on the NPM next version v2.7.2

**Pull request closed without merging**
