### PR TITLE
Fix: issue with `calculateStructMembers`

### PR DESCRIPTION
**Pull request by ElijahVlasov**
Fix: issue with `calculateStructMembers`

### CODE REVIEW

**Comment by janek26** [comment]
will this account for nested structs? and if so, could you put a test?

**Comment by ElijahVlasov** [comment]
> will this account for nested structs? and if so, could you put a test?

This accounts for nested ones. Size of a struct in the abi is its actual word size

**Comment by ElijahVlasov** [comment]
> will this account for nested structs? and if so, could you put a test?

Yes, I'll adapt my code for an example. Similar issue happens with `parseResponseStruct` method. It doesn't parse nested tuples correctly. Should I make a separate PR for that?

**Comment by tabaktoni** [comment]
@ElijahVlasov Can you rebase and add a test for this one so we can close it?

**Comment by tabaktoni** [comment]
Close in favor of https://github.com/0xs34n/starknet.js/pull/498

**Pull request closed without merging**
