### PR TITLE
feat: add checksum addresses

### PR DESCRIPTION
**Pull request by janek26**

### CODE REVIEW

**Review by 0xs34n — CHANGES_REQUESTED** [review]

**Comment by janek26** [comment]
waiting for review by StarkWare before merging

**Comment by MilGard91** [comment]
Can we also put this in the docs, under `Utils`, so we slowly start fill that too?

**Comment by greenlucid** [comment]
Sorry for pushing a yarn.lock when removing ledger libs

**Comment by janek26** [comment]
> Sorry for pushing a yarn.lock when removing ledger libs

no worries at all!

**Comment by janek26** [comment]
@MilGard91 docs added, please review

**Review by MilGard91 — APPROVED** [review]

**Pull request merged**
